### ISSUE TITLE
Missing client token

### ISSUE THREAD

**Issue by wasbazi** [ekristen/node-vault-js#2]
When using the read functionality I am getting back an error of 'missing client token' even after I have supplied it. Using straight bash with the token and vault url provides the expected data. I believe that the token is supposed to be passed with the header `X-Vault-Token: SOME_TOKEN`

Code I'm running:

``` javascript
  var vault = new Vault({
    endpoint: process.env.VAULT_URL,
    token: process.env.VAULT_TOKEN
  })

  vault.read('secret/test/message', function (err, val) {
    if (err) {
      throw err
    }

    console.log(val)
  })
```

Error I see:

``` bash
~/Code/vault-node
»  DEBUG=vault node index.js
  vault read secret/test/message +0ms
  vault GET https://MY_VAULT_CLUSER:8200/v1/secret/test/message +3ms
  vault requestOptions: {"jar":{"_jar":{"version":"tough-cookie@2.2.1","storeType":"MemoryCookieStore","rejectPublicSuffixes":true,"cookies":[{"key":"token","value":"SOME_TOKEN","domain":"MY_VAULT_CLUSTER","path":"/","hostOnly":true,"pathIsDefault":true,"creation":"2016-02-01T18:35:13.281Z","lastAccessed":"2016-02-01T18:35:13.281Z"}]}},"method":"GET","json":null,"uri":"MY_VAULT_CLUSTER:8200/v1/secret/test/message","followRedirects":true,"followAllRedirects":true} +2ms
  vault headers: {"content-type":"application/json","date":"Mon, 01 Feb 2016 18:35:13 GMT","content-length":"36","connection":"close"} +433ms
  vault RES 400 +0ms
  vault { errors: [ 'missing client token' ] } +0ms
/Users/avi/Code/vault-node/index.js:22
        throw err
              ^
Error: missing client token
    at /Users/avi/Code/vault-node/node_modules/node-vault-js/vault.js:156:13
    at Request._callback (/Users/avi/Code/vault-node/node_modules/node-vault-js/vault.js:208:12)
    at Request.self.callback (/Users/avi/Code/vault-node/node_modules/request/request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/avi/Code/vault-node/node_modules/request/request.js:1036:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/avi/Code/vault-node/node_modules/request/request.js:963:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
~/Code/vault-node
»
```

**Comment by ekristen** [comment]
I just checked out the latest code and ran your example and everything works just fine, except for you have a typo in your example with pulling in the process.env.VAULT_URL.

```
var Vault = require('./vault.js')
var vault = new Vault({
    endpoint: 'http://localhost:8200',
    token: 'xxx-xxx-xxx-xxx',
  })

  vault.read('secret/test/message', function (err, val) {
    if (err) {
      return console.log(err.stack)

    }

    console.log(val)
  })
```

**Comment by wasbazi** [comment]
I do have a typo, thanks for catching that! I'll update the issue.

**Comment by theage** [comment]
I came across this error as well and double-checked my input, all correct.
Apparently, cookie token auth has been removed since 0.3, as documented in the [change log](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md).

> Cookie Authentication Removed: As of 0.3 the only way to authenticate is via the X-Vault-Token header. Cookie authentication was hard to properly test, could result in browsers/tools/applications saving tokens in plaintext on disk, and other issues. [GH-564]

**Comment by adamflater** [comment]
For anyone still hunting this down, this worked for me today: 

```javascript
process.env.VAULT_SKIP_VERIFY = 'true'
```
